Number of subjects: 40055
Number of subjects after checking: 39373
Number of subjects: 40055
Number of subjects after checking: 39373
Traceback (most recent call last):
  File "main_train_1.py", line 42, in <module>
    model = SFCN(model_dims, 1).to(device)
  File "/home/lidfer/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 899, in to
    return self._apply(convert)
  File "/home/lidfer/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/lidfer/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/lidfer/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/lidfer/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 593, in _apply
    param_applied = fn(param)
  File "/home/lidfer/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 897, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.